sitkatech/wadnrforesthealth

- Source/ProjectFirma.Web/Controllers/AgreementController.cs
Agreement Types and Grants are now sorted by name
> [wa_dnr_forest_health_tracker/#1477] Import Agreement Types

- Source/ProjectFirma.Web/Views/Grant/Detail.cshtml
- Source/ProjectFirma.Web/Views/Grant/EditGrant.cshtml
- Source/ProjectFirma.Web/Views/Grant/EditGrantNote.cshtml
- Source/ProjectFirma.Web/Views/Grant/GrantAllocationGridSpec.cs
- Source/ProjectFirma.Web/Views/Grant/GrantGridSpec.cs
- Source/ProjectFirma.Web/Views/Grant/GrantIndex.cshtml
- Source/ProjectFirma.Web/Views/GrantAllocation/Detail.cshtml
- Source/ProjectFirma.Web/Views/GrantAllocation/EditGrantAllocationNote.cshtml
fixing some UI/UX items on the grants
> [wa_dnr_forest_health_tracker/#1455] Add/edit "parent" grants

- Source/ProjectFirma.Web/Security/PendingProjectsViewListFeature.cs
- Source/ProjectFirma.Web/Security/ProjectApproveFeature.cs
Fixing SecurityFeatureMustHaveDescription unit test
> WADNR unit test fix -- SecurityFeatureMustHaveDescription

- Database/ReleaseScript/0299 - AgreementType table - Add Nondisclosure Agreement and Task Order to the table.sql
- Database/ReleaseScript/0306 - setting agreementTypeID to be not null.sql
adding amendment agreement type and forcing agreement type to be not null on agreement table
> [wa_dnr_forest_health_tracker/#1470] Import Agreements

- Source/ProjectFirma.Web/Views/Agreement/Detail.cshtml
fixed issue with error bubble due to duplicate IDs on the page
> [wa_dnr_forest_health_tracker/#1473] Show Agreement Details page

- Source/ProjectFirma.Web/Views/Shared/InvoiceControls/InvoiceBasics.cshtml
updated view to show PurchaseAuthorityDisplay which properly show landowner if that is the case
> [wa_dnr_forest_health_tracker/#1526] Provide a way to create an invoice

- Database/Objects/Procs/pProjectCodeImportJson.sql
- Database/ReleaseScript/0383 - Remove leading zeros from ProjectCode.sql
- Source/ProjectFirma.Web/ScheduledJobs/SocrataDataMartUpdateBackgroundJob.cs
removing leading zeros from project code
> [wa_dnr_forest_health_tracker/#1603] Fix project code leading zeros

- Source/ProjectFirma.Web/Controllers/GrantController.cs
- Source/ProjectFirma.Web/Models/GrantModelExtensions.cs
- Source/ProjectFirma.Web/Views/Grant/NewGrant.cshtml
- Source/ProjectFirma.Web/Views/Grant/NewGrantViewModel.cs
* Removing field Total Award Amount from Create New Grant editor
> WADNR-1716 - Link Grant Modifications to Grant Allocations

- Database/ReleaseScript/445 - reorganizing the data model for grant modifications.sql
* Change name “Initial Grant” to “Initial Award”
> WADNR-1717 - Link Grant Modifications to Grant Allocations

- Database/LookupTables/dbo.ProjectStage.sql
- Source/ProjectFirma.Web/Controllers/ProjectController.cs
- Source/ProjectFirma.Web/Controllers/ProjectCreateController.cs
- Source/ProjectFirma.Web/Models/Generated/ProjectStage.Binding.cs
- Source/ProjectFirma.Web/Models/Project.cs
- Source/ProjectFirma.Web/Models/ProjectStage.cs
- Source/ProjectFirma.Web/Views/ProjectCreate/BasicsViewData.cs
- Source/ProjectFirma.Web/Views/ProjectCreate/CustomAttributesViewData.cs
- Source/ProjectFirma.Web/Views/ProjectCreate/ProjectCreateViewData.cs
- Source/ProjectFirma.Web/Views/Shared/ProjectLocationControls/ProjectMapCustomization.cs
Show project cancelled stage on map, and rename application stage to proposed
> WADNR-1735 Update Project Stages on the Project Map

- Source/ProjectFirma.Web/Views/Project/ProjectIndexGridSpec.cs
Update Full Project List grid columns to requested columns
> WADNR-1736 Change the columns on the Full Project List

- Database/LookupTables/dbo.InteractionEventType.sql
Add new "Research and Monitoring" event type,
and change "Outreach" to "Education and Outreach",
and "Site Visit" to "Site Visit or Field Trip".
> WADNR-1749 Update Interaction/Event types

- Database/ReleaseScript/472 - make DNR staff person optional for interaction events.sql
- Database/Tables/dbo.InteractionEvent.sql
- Source/ProjectFirma.Web/Controllers/InteractionEventController.cs
- Source/ProjectFirma.Web/DatabaseEntities.csdl
- Source/ProjectFirma.Web/DatabaseEntities.ssdl
- Source/ProjectFirma.Web/Models/ApiJson/InteractionEvent.cs
- Source/ProjectFirma.Web/Models/Generated/InteractionEvent.Binding.cs
- Source/ProjectFirma.Web/Views/InteractionEvent/EditInteractionEventViewModel.cs
- Source/ProjectFirma.Web/Views/InteractionEvent/InteractionEventGridSpec.cs
Make DNR Staff Person field on interactions/events nullable
> WADNR-1750 Make DNR Staff Person optional

- Database/ReleaseScript/0485 - creating PriorityLandscapeFileResource table.sql
- Database/Tables/dbo.PriorityLandscapeFileResource.sql
- Source/ProjectFirma.Web/Controllers/PriorityLandscapeController.cs
- Source/ProjectFirma.Web/DatabaseEntities.csdl
- Source/ProjectFirma.Web/DatabaseEntities.msl
- Source/ProjectFirma.Web/DatabaseEntities.ssdl
- Source/ProjectFirma.Web/Models/Generated/DatabaseEntities.Context.Binding.cs
- Source/ProjectFirma.Web/Models/Generated/FileResource.Binding.cs
- Source/ProjectFirma.Web/Models/Generated/PriorityLandscape.Binding.cs
- Source/ProjectFirma.Web/Models/Generated/PriorityLandscapeFileResource.Binding.cs
- Source/ProjectFirma.Web/Models/Generated/PriorityLandscapeFileResource.DatabaseContextExtensions.cs
- Source/ProjectFirma.Web/Models/Generated/PriorityLandscapeFileResourcePrimaryKey.Binding.cs
- Source/ProjectFirma.Web/Models/PriorityLandscape.cs
- Source/ProjectFirma.Web/Models/PriorityLandscapeFileResource.cs
- Source/ProjectFirma.Web/ProjectFirma.Web.csproj
- Source/ProjectFirma.Web/Security/PriorityLandscapeManageFileResourceAsAdminFeature.cs
- Source/ProjectFirma.Web/Views/PriorityLandscape/Detail.cshtml
- Source/ProjectFirma.Web/Views/PriorityLandscape/DetailViewData.cs
adding File section to PriorityLandscape detail.
went with File because of previous usages on other pages
> WADNR-1773 "Documents" section for Priority Landscape Detail Page

- Source/LtInfo.Common/DhtmlWrappers/DhtmlxGridHtmlHelpersTest.VerifyJavascriptForDhtmlxGrid.approved.txt
* update approval test with new changes
> WADNR-1795 Add progress indicator to Full Project List

- Database/ReleaseScript/0568 - add new column for prioritylandscapecategory and lookup table.sql
- Source/ProjectFirma.Web/Models/Generated/PriorityLandscapeCategory.Binding.cs
- Source/ProjectFirma.Web/Views/PriorityLandscape/Detail.cshtml
Updated eastern PL leaflet name, changed PL basic section column sizes to keep PL Category row on the same line.
> WADNR-1893 - Update Priority Landscapes map layer

- Database/ReleaseScript/0599 - adding Notes to ProjectImportBlockList.sql
- Database/Tables/dbo.ProjectImportBlockList.sql
- Source/ProjectFirma.Web/Controllers/ProgramController.cs
- Source/ProjectFirma.Web/Controllers/ProjectImportBlockListController.cs
- Source/ProjectFirma.Web/DatabaseEntities.csdl
- Source/ProjectFirma.Web/DatabaseEntities.msl
- Source/ProjectFirma.Web/DatabaseEntities.ssdl
- Source/ProjectFirma.Web/Models/Generated/ProjectImportBlockList.Binding.cs
- Source/ProjectFirma.Web/Views/Program/EditProjectImportBlockList.cshtml
- Source/ProjectFirma.Web/Views/Program/EditProjectImportBlockListViewData.cs
- Source/ProjectFirma.Web/Views/Program/EditProjectImportBlockListViewModel.cs
- Source/ProjectFirma.Web/Views/Program/ProjectBlockListGridSpec.cs
- Source/ProjectFirma.Web/Views/Program/ProjectListGridSpec.cs
- Adding Notes column
- Updating Project Import Block List form to require Notes
> WADNR-1902 Provide Admin ability to block projects from bulk import

- Database/ReleaseScript/0643 - adding content field to DNR Upland Regions.sql
- Database/Tables/dbo.DNRUplandRegion.sql
- Database/Tables/dbo.DNRUplandRegionContentImage.sql
- Source/ProjectFirma.Web/Controllers/DNRUplandRegionController.cs
- Source/ProjectFirma.Web/Controllers/FileResourceController.cs
- Source/ProjectFirma.Web/DatabaseEntities.csdl
- Source/ProjectFirma.Web/DatabaseEntities.msl
- Source/ProjectFirma.Web/DatabaseEntities.ssdl
- Source/ProjectFirma.Web/Models/County.cs
- Source/ProjectFirma.Web/Models/Generated/DNRUplandRegion.Binding.cs
- Source/ProjectFirma.Web/Models/Generated/DNRUplandRegionContentImage.Binding.cs
- Source/ProjectFirma.Web/Models/Generated/DNRUplandRegionContentImage.DatabaseContextExtensions.cs
- Source/ProjectFirma.Web/Models/Generated/DNRUplandRegionContentImagePrimaryKey.Binding.cs
- Source/ProjectFirma.Web/Models/Generated/DatabaseEntities.Context.Binding.cs
- Source/ProjectFirma.Web/Models/Generated/FileResource.Binding.cs
- Source/ProjectFirma.Web/Models/Project.cs
- Source/ProjectFirma.Web/Models/ProjectModelExtensions.cs
- Source/ProjectFirma.Web/ProjectFirma.Web.csproj
- Source/ProjectFirma.Web/Views/DNRUplandRegion/Detail.cshtml
- Source/ProjectFirma.Web/Views/DNRUplandRegion/DetailViewData.cs
- Source/ProjectFirma.Web/Views/DNRUplandRegion/EditPageContent.cs
- Source/ProjectFirma.Web/Views/DNRUplandRegion/EditPageContent.cshtml
- Source/ProjectFirma.Web/Views/DNRUplandRegion/EditPageContentViewData.cs
- Source/ProjectFirma.Web/Views/DNRUplandRegion/EditPageContentViewModel.cs
- Source/ProjectFirma.Web/Views/DNRUplandRegion/ProjectInfoGridSpecForRegionDetail.cs
got rest of columns added to project grid
added rich text to top of pages with editors
> WADNR-2073 Analyze LOA Tabular Import errors

- Source/ProjectFirma.Web/Controllers/AccountController.cs
- Purged other base roles when processing MapRoleFromClaims() role
> WADNR-2083 Fix crash on User Index page

- Database/LookupTables/dbo.ProjectCreateSection.sql
- Database/LookupTables/dbo.ProjectUpdateSection.sql
- Source/ProjectFirma.Web/Controllers/ProjectCreateController.cs
- Source/ProjectFirma.Web/Controllers/ProjectUpdateController.cs
- Source/ProjectFirma.Web/Models/Generated/ProjectCreateSection.Binding.cs
- Source/ProjectFirma.Web/Models/Generated/ProjectUpdateSection.Binding.cs
- Source/ProjectFirma.Web/Models/ProjectCreateSection.cs
- Source/ProjectFirma.Web/Models/ProjectUpdateSection.cs
- Source/ProjectFirma.Web/Views/ProjectCreate/CustomAttributesViewData.cs
- Source/ProjectFirma.Web/Views/ProjectUpdate/CustomAttributesViewData.cs
* Hide project attributes section
> WADNR-2089-Hide_Project_Attributes_section_create_Update_workflows

- Source/ProjectFirma.Web/Views/Program/EditCrosswalkValues.cshtml
- Source/ProjectFirma.Web/Views/Program/EditCrosswalkValuesController.js
- Source/ProjectFirma.Web/Views/Program/EditDefaultMappings.cshtml
- Source/ProjectFirma.Web/Views/Program/EditImportBasicsViewModel.cs
removed unneeded required tag on checkbox
fixed column spacing
fixed check for enabling add buttons for crosswalk editor and properly selecting first item in list
> WADNR-1801 Allow editing of GDB Import Rules for a Program
